// templates/frontends/angular/src/app/app.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
})
export class App {
  message = signal('');
  loading = signal(true);
  error = signal(false);

  constructor() {
    this.reload();
  }

  // Re-fetch the API message without reloading the page (the SPA model).
  reload(): void {
    this.loading.set(true);
    this.error.set(false);
    fetch('/api/hello')
      .then(res => {
        if (!res.ok) throw new Error(`Request failed: ${res.status}`);
        return res.json();
      })
      .then(data => {
        this.message.set(data.message);
        this.loading.set(false);
      })
      .catch(() => {
        this.error.set(true);
        this.loading.set(false);
      });
  }
}

// node-react/web/src/App.jsx
import { useEffect, useState } from 'react';

export default function App() {
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch('/api/hello')
      .then((res) => {
        if (!res.ok) throw new Error(`Request failed: ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setMessage(data.message);
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }, []);

  return (
    <main>
      {loading && <p>Loading…</p>}
      {error && <h1>Could not reach the API</h1>}
      {!loading && !error && <h1>{message}</h1>}
      <p>React + Vite client</p>
    </main>
  );
}
