// python-vue/web/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'

const message = ref('')
const error = ref('')
const loading = ref(true)

onMounted(async () => {
  try {
    const response = await fetch('/api/hello')
    if (!response.ok) {
      throw new Error(`Request failed with status ${response.status}`)
    }
    const data = await response.json()
    message.value = data.message
  } catch (err) {
    error.value = 'Could not reach the API'
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <main>
    <p v-if="loading">Loading…</p>
    <p v-else-if="error">{{ error }}</p>
    <h1 v-else>{{ message }}</h1>
    <p class="subtitle">Vue + Vite client</p>
  </main>
</template>

// node-react/web/src/App.jsx
import { useEffect, useState } from 'react';

export default function App() {
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch('/api/hello')
      .then((res) => {
        if (!res.ok) throw new Error(`Request failed: ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setMessage(data.message);
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }, []);

  return (
    <main>
      {loading && <p>Loading…</p>}
      {error && <h1>Could not reach the API</h1>}
      {!loading && !error && <h1>{message}</h1>}
      <p>React + Vite client</p>
    </main>
  );
}
